config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'register', to: 'users#new'
  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  get 'sign_out', to: 'sessions#destroy'
  get 'stats', to: 'home#stats'

  resources :users
  resources :sessions, only: [:create]
  resources :reputations
end

app/models/reputation.rb
class Reputation < ActiveRecord::Base
  validates :receiver_id, :sender_id, :reason, presence: true

  belongs_to :receiver, class_name: "User"
  belongs_to :sender, class_name: "User"

  scope :monthly_limitation, ->(user) { where(sender: user).where(created_at: Time.now.beginning_of_month..Time.now.end_of_month) }

  scope :last_month, -> { where(created_at: Time.now.last_month.beginning_of_month..Time.now.last_month.end_of_month) }

  paginates_per 25
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password, :name, presence: true
  validates :email, uniqueness: true
  validates :name, uniqueness: true

  has_many :reputations, foreign_key: :receiver_id

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user
    redirect_to sign_in_path if !current_user
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  MONTHLY_JCB_NUMBER = 10

  def index
    @reputations = Reputation.order(created_at: :desc).page(params[:page])
    @jcb_left_this_month = MONTHLY_JCB_NUMBER - Reputation.monthly_limitation(current_user).length
  end

  def stats
    @users = User.all
  end
end

app/controllers/reputations_controller.rb
class ReputationsController < ApplicationController
  before_filter :monthly_reputation_limitation, only: [:create]
  before_filter :authenticate_user

  MONTHLY_JCB_NUMBER = 10

  def new
    @reputation = Reputation.new
  end

  def create
    @reputation = Reputation.new(reputation_params)
    @reputation.sender = current_user
    if @reputation.save
      flash[:success] = "Thank you!"
      redirect_to root_path
    else
      flash[:error] = "Sorry, please check your input."
      render :new
    end
  end

  private
  def reputation_params
    params.require(:reputation).permit(:receiver_id, :sender_id, :reason)
  end

  def monthly_reputation_limitation
    if Reputation.monthly_limitation(current_user).length >= MONTHLY_JCB_NUMBER
      flash[:error] = "You have used all your JCB in this month."
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to root_path if current_user
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, :notice => "Logged in!"
    else
      flash[:error] = "Invalid email or password"
      redirect_to sign_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Thanks for registering JCB, please sign in."
      redirect_to sign_in_path
    else
      flash[:error] = "Please check your input."
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    current_user.update_attribute(:name, user_params[:name])
    flash[:success] = "Your name has been changed."
    render :edit
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_left_panel.html.haml
.left-panel
  .left-panel-header
    JCBs
  - @reputations.each do |reputation|
    .reputation
      .sender-name
        = reputation.sender.name
      %span.glyphicon.glyphicon-thumbs-up
      .receiver-name
        = reputation.receiver.name
      at
      .date
        = reputation.created_at.strftime("%Y-%m-%d")
      .reason
        = reputation.reason

  .left-panel-footer.clearfix
    .paginate
      = paginate @reputations

app/views/home/_right_panel.html.haml
.right-panel
  You have
  = @jcb_left_this_month
  JCB to use this month.

.right-panel
  %a{:href => new_reputation_path, style: 'text-decoration: none;'}
    %button{class: 'btn btn-success btn-block'}
      Want give a JCB to someone?

app/views/home/index.html.haml
.container
  .row
    .col-md-9
      = render 'left_panel'
    .col-md-3
      = render 'right_panel'

app/views/home/stats.html.haml
.container
  .row
    .col-md-9
      .left-panel
        .left-panel-header
          %p
            = Time.now.last_month.strftime("%Y-%m")
          - @users.each do |user|
            %p
              %h4
                = user.name
                (
                = user.reputations.last_month.length
                )
              - user.reputations.last_month.each do |r|
                %p
                  "
                  = r.reason
                  " from
                  = r.sender.name
    .col-md-3
      = render 'right_panel'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JCB
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'shared/header'
    = yield

app/views/reputations/new.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      = render "shared/messages"
      .sign-up.bg-white
        .sign-up-title
          Give a JCB to your colleague
        .sign-up-body
          = form_for(@reputation, class: 'sign_up') do |f|
            .form-group
              = f.label :recevier_id, class: 'control-label'
              = f.select :receiver_id, User.where.not(id: current_user.id).collect { |u| [u.name, u.id] }, {}, { class: 'form-control' }
            .form-group
              = f.label :reason, class: 'control-label'
              = f.text_field :reason, class: 'form-control'
            = f.submit 'I want to give it my colleague', class: 'btn btn-success', ":data-disable-with": 'Please wait...'

app/views/shared/_header.html.haml
%nav.navbar.navbar-default.navbar-static-top.bg-white{role: 'navigation'}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path} JCB
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => stats_path } Stats
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              = current_user.name
              %b.caret
            %ul.dropdown-menu
              %li
                %a{:href => edit_user_path(current_user.id)} Profile
              %li
                %a{:href => "#"} Reset Password
              %li
                = link_to 'Sign out', sign_out_path
        - else
          %li.dropdown
            = link_to 'Sign up', register_path
          %li.dropdown
            = link_to 'Sign in', sign_in_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-warning")
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
    = content_tag :div, msg, class: name

app/views/users/edit.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      = render "shared/messages"
      .sign-up.bg-white
        .sign-up-title
          Change your user name
        .sign-up-body
          = form_for(current_user, class: 'sign_up') do |f|
            .form-group
              = f.text_field :name, placeholder: 'Name', class: 'form-control'
            = f.submit 'Update', class: 'btn btn-success'

app/views/users/new.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      = render "shared/messages"
      .sign-up.bg-white
        .sign-up-title
          Sign up
        .sign-up-body
          = form_for(@user, class: 'sign_up') do |f|
            .form-group
              = f.label :email, class: 'control-label'
              = f.text_field :email, placeholder: 'Email', class: 'form-control'
            .form-group
              = f.label :name, class: 'control-label'
              = f.text_field :name, placeholder: 'Name', class: 'form-control'
            .form-group
              = f.label :password, class: 'control-label'
              = f.password_field :password, placeholder: 'Password', class: 'form-control'
            .form-group
              = f.label :password_confirmation, class: 'control-label'
              = f.password_field :password_confirmation, placeholder: 'Confirm your password', class: 'form-control'
            = f.submit 'Create', class: 'btn btn-success'